"""Add plan field to User model

Revision ID: af46996bb839
Revises: 5fcd1359a70a
Create Date: 2026-03-01 18:02:17.544258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af46996bb839'
down_revision: Union[str, Sequence[str], None] = '5fcd1359a70a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plan', sa.String(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE users SET plan = 'FREE' WHERE plan IS NULL")
    # Make the column non-nullable after setting defaults
    op.alter_column('users', 'plan', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plan')
    # ### end Alembic commands ###
